#!/bin/bash
# =============================================================================
# exam_day_checklist.sh
# Day 30: Final Exam Day Logistics
# 30-Day Terraform Challenge | AWS AI/ML UserGroup Kenya | EveOps
# =============================================================================

echo "=================================================================="
echo "EXAM DAY CHECKLIST — Terraform Associate Certification"
echo "30-Day Terraform Challenge | Day 30"
echo "=================================================================="
echo ""
echo "LOGISTICS:"
echo "  [x] Exam registered at hashicorp.com/certification"
echo "  [x] Exam format confirmed: Online proctored (PSI platform)"
echo "  [x] Room: quiet, cleared desk, no second monitors"
echo "  [x] Webcam: tested and working"
echo "  [x] Government ID: ready"
echo "  [x] Exam policies reviewed (no notes, browser locked)"
echo "  [x] Score delivery: Credly badge within 24 hours"
echo ""
echo "EXAM FACTS:"
echo "  Duration:       60 minutes"
echo "  Questions:      57"
echo "  Passing score:  70% (40/57)"
echo "  Format:         Multiple choice and multiple select"
echo ""
echo "FIVE-EXAM PREPARATION SUMMARY:"
echo "  Exam 1 (Day 28): 42/57 = 73.7%"
echo "  Exam 2 (Day 28): 45/57 = 78.9%"
echo "  Exam 3 (Day 29): 46/57 = 80.7%"
echo "  Exam 4 (Day 29): 48/57 = 84.2%"
echo "  Exam 5 (Day 30): 50/57 = 87.7%"
echo "  Average:         81.0%"
echo "  Improvement:     +14.0 points"
echo ""
echo "EXAM MORNING STRATEGY (20-min review):"
echo "  1. terraform state rm vs destroy vs import vs refresh"
echo "  2. CLI workspace vs TF Cloud workspace; terraform.workspace string"
echo "  3. Version constraint ~> operator: segment count = tightness"
echo "  4. lifecycle: prevent_destroy blocks terraform only, not console"
echo "  5. Workflow order: init -> validate -> plan -> apply; fmt is always safe"
echo ""
echo "DURING EXAM:"
echo "  - Complete all 57 questions in first pass"
echo "  - Flag uncertain questions, do not skip"
echo "  - Return to flagged questions with remaining time"
echo "  - Read scenario questions twice before answering"
echo "  - For 'which command' questions: eliminate wrong behaviours first"
echo ""
echo "=================================================================="
echo "You are ready. Go pass the exam."
echo "=================================================================="